# Generated by Django 4.2.13 on 2024-06-03 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FoodItem',
            fields=[
                ('food_id', models.AutoField(primary_key=True, serialize=False)),
                ('food_name', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=200, unique=True)),
                ('price', models.FloatField()),
                ('food_type', models.IntegerField(choices=[(0, 'Starters'), (1, 'Mains'), (2, 'Desserts'), (3, 'New')], default=3)),
                ('available', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['-food_type'],
            },
        ),
    ]
