# Generated by Django 4.2.13 on 2024-06-17 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-event_name'],
            },
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('booking_id', models.AutoField(default=1, primary_key=True, serialize=False)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, null=True, region=None)),
                ('status', models.CharField(choices=[('Awaiting confirmation', 'Awaiting Confirmation'), ('Booking Confirmed', 'Booking Confirmed'), ('Booking Rejected', 'Booking Rejected'), ('Booking Expired', 'Booking Expired')], default='awaiting confirmation', max_length=25)),
                ('email', models.EmailField(default='', max_length=254)),
                ('requested_date', models.DateField()),
                ('requested_time', models.TimeField()),
                ('number_of_people', models.IntegerField()),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='booking.service')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-requested_time'],
                'unique_together': {('requested_date', 'requested_time', 'service')},
            },
        ),
    ]
