# Generated by Django 4.2.13 on 2024-06-13 22:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0002_event_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='image',
            new_name='event_image',
        ),
    ]
