# Generated by Django 4.2.13 on 2024-06-13 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('event', '0003_rename_image_event_event_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.TextField(),
        ),
    ]
